language: go

go:
  - 1.8

services:
  - docker

before_script:
  - chmod +x ./scripts/*.sh

script:
  - docker-compose build
  - ./scripts/deps.sh
  - ./scripts/tests.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)